#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../college-success/collegesuccess_recipe'

hs = Kitchen::BookRecipe.new(book_short_name: :hs_college_success) do |doc|
  include Kitchen::Directions

  book = doc.book
  metadata = book.metadata

  book.search('cnx-pi').trash

  BakeAutotitledNotes.v1(
    book: book,
    classes: %w[
      family-friends
      checking-in
      real-deal
      student-story
    ]
  )
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Baked XHTML output file', required: true
  slop.string '--resources', 'Path to book resources directory', required: false
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: [COLLEGESUCCESS_RECIPE, hs, VALIDATE_OUTPUT],
  output_file: opts[:output],
  resource_dir: opts[:resources] || nil
)
