#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../recipes_helper'

recipe = Kitchen::BookRecipe.new(book_short_name: :organic_chemistry) do |doc|
  include Kitchen::Directions

  book = doc.book
  metadata = book.metadata

  # Some stuff just goes away
  book.search('cnx-pi').trash

  BakeUnnumberedFigure.v1(book: book)
  BakePreface.v1(book: book)

  AddInjectedExerciseId.v1(book: book)
  book.injected_exercises.each do |exercise|
    BakeInjectedExercise.v1(exercise: exercise, alphabetical_multiparts: true)
  end

  answer_key_wrapper = BookAnswerKeyContainer.v1(book: book)

  book.chapters.each do |chapter|
    BakeChapterGlossary.v1(chapter: chapter, metadata_source: metadata)
    BakeChapterKeyEquations.v1(chapter: chapter, metadata_source: metadata)

    MoveCustomSectionToEocContainer.v1(
      chapter: chapter,
      metadata_source: metadata,
      container_key: 'summary',
      uuid_key: '.summary',
      section_selector: 'section.summary'
    ) do |section|
      RemoveSectionTitle.v1(section: section)
    end

    MoveCustomSectionToEocContainer.v1(
      chapter: chapter,
      metadata_source: metadata,
      container_key: 'summary-reactions',
      uuid_key: '.summary-reactions',
      section_selector: 'section.summary-reactions'
    ) do |section|
      RemoveSectionTitle.v1(section: section)
      title = EocSectionTitleLinkSnippet.v1(page: section.ancestor(:page))
      section.prepend(child: title)
    end

    MoveExercisesToEOC.v1(chapter: chapter, metadata_source: metadata,
                          klass: 'visualizing-chemistry')
    MoveExercisesToEOC.v1(chapter: chapter, metadata_source: metadata,
                          klass: 'additional-problems')
    BakeChapterSectionExercises.v1(
      chapter: chapter,
      options: {
        trash_title: true,
        create_title: false
      }
    )

    MoveCustomSectionToEocContainer.v1(
      chapter: chapter,
      metadata_source: metadata,
      container_key: 'practice-scientific',
      uuid_key: '.practice-scientific',
      section_selector: 'section.practice-scientific'
    ) do |section|
      RemoveSectionTitle.v1(section: section)
      title = EocSectionTitleLinkSnippet.v1(page: section.ancestor(:page))
      section.prepend(child: title)
    end

    exercise_selectors = 'section.section-exercises, section.visualizing-chemistry, ' \
                         'section.additional-problems'

    chapter.search(exercise_selectors).injected_questions.each do |question|
      BakeInjectedExerciseQuestion.v1(question: question, number: question.count_in(:chapter))
      BakeFirstElements.v1(within: question)
    end

    # Bake answer key sections
    answer_key_inner_container = AnswerKeyInnerContainer.v1(
      chapter: chapter, metadata_source: metadata, append_to: answer_key_wrapper
    )
    chapter.non_introduction_pages.each do |page|
      page.search('div.os-eos.os-section-exercises-container').each do |section_wrapper|
        Kitchen::Directions::MoveSolutionsFromExerciseSection.v1(
          chapter: section_wrapper, append_to: answer_key_inner_container,
          section_class: 'section-exercises', options: { add_title: false }
        )
      end
    end
    %w[visualizing-chemistry additional-problems].each do |klass|
      Kitchen::Directions::MoveSolutionsFromExerciseSection.v1(
        chapter: chapter, append_to: answer_key_inner_container, section_class: klass
      )
    end
  end

  BakeChapterIntroductions.v1(book: book)
  BakeChapterTitle.v1(book: book)

  book.chapters.each do |chapter|
    BakeLearningObjectives.v1(chapter: chapter)
    BakeNonIntroductionPages.v1(chapter: chapter)

    chapter.tables('$:not(.unnumbered)').each do |table|
      BakeNumberedTable.v1(table: table,
                           number: "#{chapter.count_in(:book)}.#{table.count_in(:chapter)}")
    end

    chapter.examples.each do |example|
      BakeExample.v1(example: example,
                     number: "#{chapter.count_in(:book)}.#{example.count_in(:chapter)}",
                     title_tag: 'h3')
    end

    chapter.figures(only: :figure_to_number?).each do |figure|
      if figure.has_class?('mechanism-figure')
        BakeFigure.v1(figure: figure,
                      number: "#{chapter.count_in(:book)}.#{figure.count_in(:chapter)}",
                      custom_class: 'mechanism-figure')
      else
        BakeFigure.v1(figure: figure,
                      number: "#{chapter.count_in(:book)}.#{figure.count_in(:chapter)}")
      end
    end
  end

  book.pages('$.appendix').each do |page|
    appendix_letter = [*('A'..'Z')][page.count_in(:book) - 1]

    page.figures(only: :figure_to_number?).each do |figure|
      if figure.has_class?('mechanism-figure')
        BakeFigure.v1(figure: figure,
                      number: "#{appendix_letter}#{figure.count_in(:page)}",
                      custom_class: 'mechanism-figure')
      else
        BakeFigure.v1(figure: figure, number: "#{appendix_letter}#{figure.count_in(:page)}")
      end
    end

    page.tables('$:not(.unnumbered)').each do |table|
      BakeNumberedTable.v1(table: table, number: "#{appendix_letter}#{table.count_in(:page)}")
    end

    page.examples.each do |example|
      BakeExample.v1(example: example,
                     number: "#{appendix_letter}#{example.count_in(:page)}",
                     title_tag: 'div')
    end

    BakeAppendix.v1(page: page, number: appendix_letter)
  end

  BakeUnnumberedTables.v1(book: book)

  book.search('div[data-type="question-solution"]').each do |solution|
    BakeFirstElements.v1(within: solution)
  end

  note_classes = %w[why-chapter something-extra working-problems]
  BakeAutotitledNotes.v1(book: book, classes: note_classes)

  BakeUnclassifiedNotes.v1(book: book)
  BakeStepwise.v1(book: book)
  BakeMathInParagraph.v1(book: book)
  BakeIndex.v1(book: book)
  BakeCompositePages.v1(book: book)
  BakeFootnotes.v1(book: book)
  BakeCompositeChapters.v1(book: book)
  BakeToc.v1(book: book)
  BakeLinkPlaceholders.v1(book: book)
  BakeFolio.v1(book: book)
  BakeLinks.v1(book: book)
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Baked XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: [recipe, VALIDATE_OUTPUT],
  output_file: opts[:output]
)
