#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../recipes_helper'

recipe = Kitchen::BookRecipe.new(book_short_name: :english_composition_short) do |doc|
  include Kitchen::Directions

  book = doc.book
  # trash all but first chapter
  book.chapters.drop(1).each(&:trash)
  # trash all but first unit
  book.units.drop(1).each(&:trash)
  # trash all but first appendix
  book.search('div.appendix').drop(1).each(&:trash)
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Shortened assembled XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: recipe,
  output_file: opts[:output]
)
