files:
  # define files excluded from the analysis (defaults to [])
  excluded:
    - lib/kitchen/directions/**/*.rb # may want to add this in later in a limited way
    - lib/kitchen/debug/**/*.rb
    - lib/cookbook_kitchen.rb
