Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 100

Naming/PredicateName:
  Enabled: false

Metrics/ClassLength:
  Max: 300
  CountAsOne: ['heredoc']

Metrics/MethodLength:
  Max: 50
  CountAsOne: ['heredoc']

Metrics/BlockLength:
  CountAsOne: ['heredoc']
  Exclude:
    - *.gemspec

Metrics/ModuleLength:
  CountAsOne: ['heredoc']

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/SingleLineMethods:
  Enabled: false # don't abuse it, but sometimes it is right

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SymbolProc:
  IgnoredMethods:
    - respond_to
    - define_method
    - XML # For Nokogiri::XML

Layout/ClosingParenthesisIndentation:
  Enabled: false # when true hanging parens look weird
