AllCops:
  TargetRubyVersion: 3.2

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['(\A|\s)#']

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/ClassLength:
  Max: 300
  CountAsOne: ['heredoc']

Metrics/MethodLength:
  Max: 50
  CountAsOne: ['heredoc']

Metrics/BlockLength:
  CountAsOne: ['heredoc']
  Max: 30
  Exclude:
    - 'openstax_cookbook.gemspec'
    - 'lib/recipes/**/*'

Metrics/ModuleLength:
  CountAsOne: ['heredoc']

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/SingleLineMethods:
  Enabled: false # don't abuse it, but sometimes it is right

Style/RedundantBegin:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SymbolProc:
  AllowedMethods:
    - respond_to
    - define_method
    - XML # For Nokogiri::XML

Layout/ClosingParenthesisIndentation:
  Enabled: false # when true hanging parens look weird

Layout/MultilineMethodCallBraceLayout:
  Enabled: false
