# TODO: merge conflicts

<<<<<<< HEAD
AllCops:
  TargetRubyVersion: 2.4

=======
>>>>>>> remote-recipes/main
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LineLength:
  Max: 100
<<<<<<< HEAD
  IgnoredPatterns: ['(\A|\s)#']
=======
>>>>>>> remote-recipes/main

Metrics/AbcSize:
  Max: 50

Naming/PredicateName:
  Enabled: false

Metrics/ClassLength:
  Max: 300
  CountAsOne: ['heredoc']

Metrics/MethodLength:
  Max: 50
  CountAsOne: ['heredoc']

<<<<<<< HEAD
Metrics/BlockLength:
  CountAsOne: ['heredoc']
  Max: 30
  Exclude:
    - 'openstax_kitchen.gemspec'
=======
# Recipes have long blocks on purpose
Metrics/BlockLength:
  Enabled: false
  CountAsOne: ['heredoc']
>>>>>>> remote-recipes/main

Metrics/ModuleLength:
  CountAsOne: ['heredoc']

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/SingleLineMethods:
  Enabled: false # don't abuse it, but sometimes it is right

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SymbolProc:
  IgnoredMethods:
    - respond_to
    - define_method
    - XML # For Nokogiri::XML

Layout/ClosingParenthesisIndentation:
  Enabled: false # when true hanging parens look weird
<<<<<<< HEAD

Layout/MultilineMethodCallBraceLayout:
  Enabled: false
=======
>>>>>>> remote-recipes/main
