#!/usr/bin/env bash

usage="bake -r <legacy_recipe_file> -i <inputfile> -o <outputfile>"

# Get command line arguments

while getopts i:o:r:h flag
do
  case "${flag}" in
    i) input_file=${OPTARG} ;;
    o) output_file=${OPTARG} ;;
    r) legacy_recipe_file=${OPTARG} ;;
    h) echo "$usage"; exit 0 ;;
    *) echo "Unknown flag '${flag}'"; exit 1 ;;
  esac
done

cnx-easybake -q "$legacy_recipe_file" "$input_file" "$output_file"
