#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

usage="bake -b <bookname> -i <inputfile> -o <outputfile>"

# Get command line arguments

while getopts b:i:o:r:h flag
do
  case "${flag}" in
    b) book=${OPTARG} ;;
    i) input_file=${OPTARG} ;;
    o) output_file=${OPTARG} ;;
    h) echo "$usage"; exit 0 ;;
    *) echo "Unknown flag '${flag}'"; exit 1 ;;
  esac
done

# Bake book

echo "Baking book '${book}'" ;
"${DIR}/bake" -b "$book" -i "$input_file" -o "$output_file";;
