#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

usage="bake -b <bookname> -i <inputfile> -o <outputfile>"

# Get command line arguments

while getopts b:i:o:h flag
do
  case "${flag}" in
    b) book=${OPTARG} ;;
    i) input_file=${OPTARG} ;;
    o) output_file=${OPTARG} ;;
    h) echo $usage; exit 0 ;;
    *) echo "Unknown flag '${flag}'"; exit 1 ;;
  esac
done

# Call the baking script based on the book; books will probably have the same
# calling syntax, but maybe not so don't try to reduce duplication here.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

case "${book}" in
  dummy) $DIR/books/dummy/bake --input $input_file --output $output_file;;
  pl-psychology) $DIR/books/pl-psychology/bake --input $input_file --output $output_file;;
  american_government) $DIR/books/american_government/bake --input $input_file --output $output_file;;
  ap-history) $DIR/books/ap-history/bake --input $input_file --output $output_file;;
  calculus) $DIR/books/calculus/bake --input $input_file --output $output_file;;
  chemistry) $DIR/books/chemistry/bake --input $input_file --output $output_file;;
  statistics) $DIR/books/statistics/bake --input $input_file --output $output_file;;
  contemporary-math) $DIR/books/contemporary-math/bake --input $input_file --output $output_file;;
  precalculus) $DIR/books/precalculus/bake --input $input_file --output $output_file;;
  precalculus-coreq) $DIR/books/precalculus-coreq/bake --input $input_file --output $output_file;;
  anthropology) $DIR/books/anthropology/bake --input $input_file --output $output_file;;
  biology) $DIR/books/biology/bake --input $input_file --output $output_file;;
  political-science) $DIR/books/political-science/bake --input $input_file --output $output_file;;
  philosophy) $DIR/books/philosophy/bake --input $input_file --output $output_file;;
  microbiology) $DIR/books/microbiology/bake --input $input_file --output $output_file;;
  sociology) $DIR/books/sociology/bake --input $input_file --output $output_file;;
  english-composition) $DIR/books/english-composition/bake --input $input_file --output $output_file;;
  u-physics) $DIR/books/u-physics/bake --input $input_file --output $output_file;;
  finance) $DIR/books/finance/bake --input $input_file --output $output_file;;
  computer-science) $DIR/books/computer-science/bake --input $input_file --output $output_file;;
  ap-biology) $DIR/books/ap-biology/bake --input $input_file --output $output_file;;
  *) echo "Unknown book '${book}'"; exit 1;;
esac
