codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 0.01%      # codecov/project fails if there is a drop of more than 0.01%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "spec"
  - "tutorials"
  - "bin"
  - "docker"
  - "books"
  - "lib/kitchen/patches/nokogiri_profiling"
