#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

usage="shorten -b <bookname> -i <inputfile>"

# Get command line arguments

while getopts b:i:h flag
do
  case "${flag}" in
    b) book=${OPTARG} ;;
    i) input_file=${OPTARG} ;;
    h) echo $usage; exit 0 ;;
    *) echo "Unknown flag '${flag}'"; exit 1 ;;
  esac
done

# List additional lib/recipes here

case "${book}" in
  american-government) dest="${DIR}/data/american-government/short" && script="${DIR}/lib/recipes/american-government/shorten";;
  ap-history) dest="${DIR}/data/ap-history/short" && script="${DIR}/lib/recipes/ap-history/shorten";;
  biology) dest="${DIR}/data/biology/short" && script="${DIR}/lib/recipes/biology/shorten";;
  calculus) dest="${DIR}/data/calculus/short" && script="${DIR}/lib/recipes/calculus/shorten";;
  chemistry) dest="${DIR}/data/chemistry/short" && script="${DIR}/lib/recipes/chemistry/shorten";;
  statistics) dest="${DIR}/data/statistics/short" && script="${DIR}/lib/recipes/statistics/shorten";;
  pl-psychology) dest="${DIR}/data/pl-psychology/short" && script="${DIR}/lib/recipes/pl-psychology/shorten";;
  microbiology) dest="${DIR}/data/microbiology/short" && script="${DIR}/lib/recipes/microbiology/shorten";;
  precalculus) dest="${DIR}/data/precalculus/short" && script="${DIR}/lib/recipes/precalculus/shorten";;
  precalculus-coreq) dest="${DIR}/data/college-algebra-coreq/short" && script="${DIR}/lib/recipes/precalculus-coreq/shorten";;
  sociology) dest="${DIR}/data/sociology/short" && script="${DIR}/lib/recipes/sociology/shorten";;
  u-physics) dest="${DIR}/data/u-physics/short" && script="${DIR}/lib/recipes/u-physics/shorten";;
  economics) dest="${DIR}/data/economics/short" && script="${DIR}/lib/recipes/economics/shorten";;
  finance) dest="${DIR}/data/finance/short" && script="${DIR}/lib/recipes/finance/shorten";;
  english-composition) dest="${DIR}/data/english-composition/short" && script="${DIR}/lib/recipes/english-composition/shorten";;
  microbiology) dest="${DIR}/data/microbiology/short" && script="${DIR}/lib/recipes/microbiology/shorten";;
  anatomy) dest="${DIR}/data/anatomy/short" && script="${DIR}/lib/recipes/anatomy/shorten";;
  bca) dest="${DIR}/data/bca/short" && script="${DIR}/lib/recipes/bca/shorten";;
  computer-science) dest="${DIR}/data/computer-science/short" && script="${DIR}/lib/recipes/computer-science/shorten";;
  political-science) dest="${DIR}/data/political-science/short" && script="${DIR}/lib/recipes/political-science/shorten";;
  ap-biology) dest="${DIR}/data/ap-biology/short" && script="${DIR}/lib/recipes/ap-biology/shorten";;
  additive-manufacturing) dest="${DIR}/data/additive-manufacturing/short" && script="${DIR}/lib/recipes/additive-manufacturing/shorten";;
  college-physics) dest="${DIR}/data/college-physics/short" && script="${DIR}/lib/recipes/college-physics/shorten";;
  astronomy) dest="${DIR}/data/astronomy/short" && script="${DIR}/lib/recipes/astronomy/shorten";;
  ap-physics) dest="${DIR}/data/ap-physics/short" && script="${DIR}/lib/recipes/ap-physics/shorten";;
  ap-physics-2e) dest="${DIR}/data/ap-physics-2e/short" && script="${DIR}/lib/recipes/ap-physics-2e/shorten";;
  history) dest="${DIR}/data/history/short" && script="${DIR}/lib/recipes/history/shorten";;
  dev-math) dest="${DIR}/data/prealgebra/short" && script="${DIR}/lib/recipes/dev-math/shorten";;
  hs-physics) dest="${DIR}/data/hs-physics/short" && script="${DIR}/lib/recipes/hs-physics/shorten";;
  college-success) dest="${DIR}/data/college-success/short" && script="${DIR}/lib/recipes/college-success/shorten";;
  psychology) dest="${DIR}/data/psychology/short" && script="${DIR}/lib/recipes/psychology/shorten";;
  entrepreneurship) dest="${DIR}/data/entrepreneurship/short" && script="${DIR}/lib/recipes/entrepreneurship/shorten";;
  intro-business) dest="${DIR}/data/intro-business/short" && script="${DIR}/lib/recipes/intro-business/shorten";;
  principles-management) dest="${DIR}/data/principles-management/short" && script="${DIR}/lib/recipes/principles-management/shorten";;
  business-ethics) dest="${DIR}/data/business-ethics/short" && script="${DIR}/lib/recipes/business-ethics/shorten";;
  accounting) dest="${DIR}/data/accounting/short" && script="${DIR}/lib/recipes/accounting/shorten";;
  philosophy) dest="${DIR}/data/philosophy/short" && script="${DIR}/lib/recipes/philosophy/shorten";;
  pl-economics) dest="${DIR}/data/pl-economics/short" && script="${DIR}/lib/recipes/pl-economics/shorten";;
  pl-u-physics) dest="${DIR}/data/pl-u-physics/short" && script="${DIR}/lib/recipes/pl-u-physics/shorten";;
  world-history) dest="${DIR}/data/world-history/short" && script="${DIR}/lib/recipes/world-history/shorten";;
  marketing) dest="${DIR}/data/marketing/short" && script="${DIR}/lib/recipes/marketing/shorten";;
  *) echo "Unknown book '${book}'"; exit 1;;
esac

# Call the shorten script

echo "Shortening ..."
if [ ! -d $dest ]
then
    mkdir $dest
fi
$script --input $input_file --output $dest/assembled.xhtml

# Bake shortened book with legacy

if [ -e legacy_recipes/$book.css ]
then
    echo "Baking with legacy ..."
    ./bake_legacy -i $dest/assembled.xhtml -r legacy_recipes/$book.css -o $dest/easybaked.xhtml
    # Normalize the easybaked book
    ruby scripts/normalize $dest/easybaked.xhtml --easybaked-only
else
    echo "Cannot bake with legacy because legacy_recipes/${book}.css does not exist."
fi

# Bake shortened book with kitchen

if [ -e $DIR/lib/recipes/$book/bake ]
then
  echo "Baking with kitchen ..."
  ./bake -b $book -i $dest/assembled.xhtml -o $dest/kitchen-baked.xhtml
  # Normalize the kitchen baked book
  ruby scripts/normalize $dest/kitchen-baked.xhtml
else
  echo "Cannot bake with kitchen because lib/recipes/${book}/bake does not exist."
fi
