#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../recipes_helper'
require_relative '../college-physics/college_physics_recipe'

college_physics_2e = Kitchen::BookRecipe.new(book_short_name: :college_physics_2e_delete) do |doc|
  include Kitchen::Directions

  book = doc.book

  book.search('section.ap-test-prep').each(&:trash)
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Shortened assembled XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: [college_physics_2e, COLLEGE_PHYSICS_RECIPE],
  output_file: opts[:output]
)
