#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../recipes_helper'
require_relative '../college-physics/college_physics_recipe'

college_physics_2e = Kitchen::BookRecipe.new(book_short_name: :college_physics_2e_delete) do |doc|
  include Kitchen::Directions

  book = doc.book
  metadata = book.metadata

  book.search('section.ap-test-prep').each(&:trash)

  answer_key = BookAnswerKeyContainer.v1(book: book)

  book.chapters.each do |chapter|
    chapter.sections('$.authentic-assessment').each do |section|
      section.prepend(child: 
        <<~HTML
          <h3 data-type="title">#{I18n.t(:"exercises.authentic-assessment")}</h3>
        HTML
      )
      section.exercises.each do |exercise|
        BakeNumberedExercise.v1(
         exercise: exercise, number: exercise.count_in(:section))
      end
    end

    chapter.sections('$.problems-exercises').exercises.each do |exercise|
      BakeNumberedExercise.v1(
        exercise: exercise, number: exercise.count_in(:chapter))
    end

    answer_key_inner_container = AnswerKeyInnerContainer.v1(
      chapter: chapter, metadata_source: metadata, append_to: answer_key
    )

    classes = %w[problems-exercises]
    classes.each do |klass|
      MoveSolutionsFromExerciseSection.v1(
        chapter: chapter, append_to: answer_key_inner_container, section_class: klass
      )
    end
  end
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Shortened assembled XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: [college_physics_2e, COLLEGE_PHYSICS_RECIPE],
  output_file: opts[:output]
)
