# frozen_string_literal: true

module Kitchen::Directions
  module BakeNumberedNotes
    class V4
      # @return [Array<String>] the ids of the notes that were baked, so callers can
      #   exclude them from any other note-baking pass over the same class(es)
      #
      def bake(book:, classes:, within:, scope:)
        baked_note_ids = []

        classes.each do |klass|
          book.chapters.pages.search(within).notes("$.#{klass}").each do |note|
            raise "missing id on note#{note.say_source_or_nil}" if note.id.blank?

            note.wrap_children(class: 'os-note-body')
            note_count = note.count_in(scope)
            note.prepend(child:
              <<~HTML
                <h3 class="os-title">
                  <span class="os-title-label">#{note.autogenerated_title}</span>
                  <span class="os-number">##{note_count}</span>
                </h3>
              HTML
            )
            note.exercises.each do |exercise|
              BakeNoteExercise.v1(note: note, exercise: exercise, divider: '. ')
            end
            note.injected_questions.each do |question|
              BakeNoteInjectedQuestion.v1(note: note, question: question)
            end
            baked_note_ids << note.id
          end
        end

        baked_note_ids
      end
    end
  end
end
