#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  gem 'openstax_kitchen', '2.0.0'
  gem 'slop', '4.8.2'
end

recipe = Kitchen::BookRecipe.new(book_short_name: :dummy) do |doc|
  include Kitchen::Directions

  book = doc.book
  book.search('div.test123').first.replace_children(with: 'Hello, world!')
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Baked XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: recipe,
  output_file: opts[:output]
)
