#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  gem 'openstax_kitchen', ENV['USE_LOCAL_KITCHEN'] ? { path: '/code/kitchen' } : '3.2.0'
  gem 'slop', '4.8.2'
  gem 'byebug'
end

recipe = Kitchen::BookRecipe.new(book_short_name: :dummy) do |doc|
  include Kitchen::Directions

  book = doc.book

  book.search('cnx-pi').trash

  BakePreface.v1(book: book)
  BakeChapterIntroductions.v1(book: book)
  BakeChapterTitle.v1(book: book)
  book.chapters.each do |chapter|
    BakePageAbstracts.v1(chapter: chapter)
    BakeNonIntroductionPages.v1(chapter: chapter)
  end

  BakeAutotitledNotes.v1(book: book, classes: %w[how-to-notitle qa media-notitle])
  BakeUnclassifiedNotes.v1(book: book)
  BakeNumberedNotes.v2(book: book, classes: %w[try])

  # Bake EOC sections
  solutions_container = BookAnswerKeyContainer.v1(book: book)
  book.chapters.each do |chapter|
    eoc_wrapper = ChapterReviewContainer.v1(chapter: chapter, metadata_source: book.metadata)

    BakeChapterGlossary.v1(chapter: chapter, metadata_source: book.metadata, append_to: eoc_wrapper)
    BakeChapterKeyEquations.v1(chapter: chapter, metadata_source: book.metadata, append_to: eoc_wrapper)
    BakeChapterKeyConcepts.v1(chapter: chapter, metadata_source: book.metadata, append_to: eoc_wrapper)
    # EoC sections with exercises
    # MoveExercisesToEOC.v2(chapter: chapter, metadata_source: book.metadata, append_to: eoc_wrapper, klass: 'review-conceptual-questions')
    # MoveExercisesToEOC.v2(chapter: chapter, metadata_source: book.metadata, append_to: eoc_wrapper, klass: 'review-problems')

    eoc_exercises_wrapper = ChapterReviewContainer.v1(chapter: chapter, metadata_source: book.metadata)
    MoveExercisesToEOC.v1(chapter: chapter, metadata_source: book.metadata, append_to: eoc_exercises_wrapper, klass: 'review-exercises')
    MoveExercisesToEOC.v1(chapter: chapter, metadata_source: book.metadata, append_to: eoc_exercises_wrapper, klass: 'practice-test')
    BakeChapterSectionExercises.v1(chapter: chapter)
    # # In-place bake exercises & solutions
    chapter.search('.review-exercises').exercises.each do |exercise|
      BakeNumberedExercise.v1(exercise: exercise, number: exercise.count_in(:chapter))
    end
    chapter.search('.practice-test').exercises.each do |exercise|
      BakeNumberedExercise.v1(exercise: exercise, number: exercise.count_in(:chapter))
    end
    chapter.pages.search('.section-exercises').exercises.each do |exercise|
      BakeNumberedExercise.v1(exercise: exercise, number: exercise.count_in(:page))
    end

    # # Bake answer key from chapter/ move solutions from eoc into answer key
    MoveSolutionsToAnswerKey.v1(chapter: chapter, metadata_source: book.metadata, strategy: :precalculus, append_to: solutions_container)
  end

  puts ''

  book.chapters.each do |chapter|
    chapter.tables('$:not(.unnumbered)').each do |table|
      BakeNumberedTable.v1(table: table,
                           number: "#{chapter.count_in(:book)}.#{table.count_in(:chapter)}")
    end
    chapter.figures('$:not(.unnumbered)').each do |figure|
      BakeFigure.v1(figure: figure,
                    number: "#{chapter.count_in(:book)}.#{figure.count_in(:chapter)}")
    end

    chapter.examples.each do |example|
      BakeExample.v1(example: example,
                     number: "#{chapter.count_in(:book)}.#{example.count_in(:chapter)}",
                     title_tag: 'h3')
    end
  end

  book.pages('$.appendix').each do |page|
    appendix_letter = [*('A'..'Z')][page.count_in(:book) - 1]
    BakeAppendix.v1(page: page, number: appendix_letter)

    page.tables('$:not(.unnumbered)').each do |table|
      BakeNumberedTable.v1(table: table, number: "#{appendix_letter}#{table.count_in(:page)}")
    end
    page.figures('$:not(.unnumbered)').each do |figure|
      BakeFigure.v1(figure: figure, number: "#{appendix_letter}#{figure.count_in(:page)}")
    end
  end

  BakeUnnumberedTables.v1(book: book)

  book.search('[data-type="exercise"], [data-type="solution"]').each do |exercise|
    # Add the 'has-first-element' class to elements that need it
    #byebug if exercise.id == "auto_11f4eacc-c348-4836-8c5b-747577d249ca_fs-id1165137644802"
    BakeFirstElements.v1(within: exercise,
                         selectors: ['.os-problem-container > [data-type="media"]',
                                     '.os-problem-container > .os-table',
                                     '.os-solution-container > [data-type="media"]',
                                     '.os-solution-container > .os-table'])
  end

  BakeMathInParagraph.v1(book: book)
  BakeIndex.v1(book: book)
  BakeFootnotes.v1(book: book)
  book.search('[role="doc-noteref"]').each do |el|
    el.parent.add_class('has-noteref') if el.parent.name == 'p'
  end
  BakeCompositePages.v1(book: book)
  BakeCompositeChapters.v1(book: book)
  BakeToc.v1(book: book)
  BakeLinkPlaceholders.v1(book: book)
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Baked XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: recipe,
  output_file: opts[:output]
)
