#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../recipes_helper'

allow_unknown = !ENV['ALLOW_UNKNOWN_ARGS'].nil?

# 1. Parse options first so variables are available inside the recipe block
opts = Slop.parse suppress_errors: allow_unknown do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Baked XHTML output file', required: true
  slop.string '--keep-chapters', 'Comma-separated list of chapter numbers to keep (e.g., "1,3,5")',
              default: '1'
end

recipe = Kitchen::BookRecipe.new(book_short_name: :ap_biology_short) do |doc|
  include Kitchen::Directions

  book = doc.book

  # trash all but first chapter
  book.units.drop(1).each(&:trash)
  book.chapters.drop(1).each(&:trash)
  # trash all but first appendix
  book.search('div.appendix').drop(1).each(&:trash)
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: [recipe],
  output_file: opts[:output]
)
