#!/usr/bin/env ruby

# frozen_string_literal: true

require 'bundler/inline'
require_relative '../../bake_helper'

gemfile do
  gem 'openstax_kitchen', \
      ENV['USE_LOCAL_KITCHEN'] ? { path: '/code/kitchen' } : KITCHEN_VERSIONS[:history]
  gem 'slop', '4.8.2'
  gem 'byebug'
end

recipe = Kitchen::BookRecipe.new(book_short_name: :history) do |doc|
  include Kitchen::Directions

  book = doc.book
  metadata = book.metadata

  # Some stuff just goes away
  book.search('cnx-pi').trash

  BakePreface.v1(book: book, title_element: 'h1')
  BakeChapterIntroductions.v1(book: book)
  BakeChapterTitle.v1(book: book)

  BakeAutotitledNotes.v1(
    book: book,
    classes: %w[click-and-explore my-story americana]
  )

  # BakeNumberedNotes.v1(
  #   book: book,
  #   classes: %w[cfa-institute]
  # )

  book.chapters.each do |chapter|
    BakeLearningObjectives.v1(chapter: chapter)
    BakeNonIntroductionPages.v1(chapter: chapter)
    BakeChapterGlossary.v1(chapter: chapter, metadata_source: metadata)
    BakeChapterSummary.v1(chapter: chapter, metadata_source: metadata)

    eoc_sections = %w[review-questions critical-thinking]

    chapter.pages.search("section.review-questions").exercises.each_with_index do |exercise, index|
      if index.odd?
        BakeNumberedExercise.v1(
          exercise: exercise,
          number: exercise.count_in(:chapter),
          suppress_solution_if: true,
          note_suppressed_solutions: true
        )
      else
        BakeNumberedExercise.v1(exercise: exercise, number: exercise.count_in(:chapter))
      end
    end

    eoc_sections.each do |klass|
      chapter.pages.search("section.#{klass}").exercises.each_with_index do |exercise|
        BakeNumberedExercise.v1(exercise: exercise, number: exercise.count_in(:chapter))
      end
    end

    answer_key = BookAnswerKeyContainer.v1(book: book)
    # Bake answer key from chapter/ move solutions from eoc into answer key
    MoveSolutionsToAnswerKey.v1(
      chapter: chapter,
      metadata_source: metadata,
      strategy: :history,
      append_to: answer_key,
      solutions_plural: false
    )

    eoc_sections.each do |section_key|
      MoveCustomSectionToEocContainer.v1(
        chapter: chapter,
        metadata_source: metadata,
        container_key: section_key,
        uuid_key: ".#{section_key}",
        section_selector: "section.#{section_key}"
      ) do |section|
        RemoveSectionTitle.v1(section: section)
      end
    end

  #   exercise_section_classes = %w[video-activity]
  #   chapter.search(exercise_section_classes.prefix('section.').join(', ')).each do |element|
  #     BakeIframes.v1(outer_element: element)
  #   end

  #   chapter.tables('$:not(.unnumbered)').each do |table|
  #     BakeNumberedTable.v1(table: table,
  #                          number: "#{chapter.count_in(:book)}.#{table.count_in(:chapter)}")
  #   end

    chapter.figures('$:not(.unnumbered)').each do |figure|
      BakeFigure.v1(figure: figure,
                    number: "#{chapter.count_in(:book)}.#{figure.count_in(:chapter)}")
    end
  end

  book.pages('$.appendix').each do |page|
    appendix_letter = [*('A'..'Z')][page.count_in(:book) - 1]

    page.figures.each do |figure|
      BakeFigure.v1(figure: figure, number: "#{appendix_letter}#{figure.count_in(:page)}")
    end

    page.tables('$:not(.unnumbered)').each do |table|
      BakeNumberedTable.v1(table: table, number: "#{appendix_letter}#{table.count_in(:page)}")
    end

    BakeAppendix.v1(page: page, number: appendix_letter)
  end

  # BakeStepwise.v1(book: book)
  # BakeUnnumberedTables.v1(book: book)
  # BakeMathInParagraph.v1(book: book)
  BakeIndex.v1(book: book)
  BakeCompositePages.v1(book: book)
  # BakeFootnotes.v1(book: book)
  BakeCompositeChapters.v1(book: book)
  BakeToc.v1(book: book)
  # BakeLinkPlaceholders.v1(book: book)
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Baked XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: recipe,
  output_file: opts[:output]
)
