#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# See https://docs.codecov.io/docs/testing-with-docker, also note that it is
# critical to set CI=true because codecov-ruby won't detect GitHub Actions
# without it per:
# https://github.com/codecov/codecov-ruby/blob/484767f1c3d7992a9d7fedd6dc72d35a80d04f70/lib/codecov.rb#L68-L69

# CODECOV_TOKEN is added to repo settings according to:
# https://github.com/openstax/cnx-recipes/issues/5516
# https://docs.codecov.com/docs/adding-the-codecov-token#github-actions

docker run $CI_ENV \
           -e ENABLE_CODECOV=1 -e CI=true \
           -e CODECOV_TOKEN=${CODECOV_TOKEN} \
           -v $DIR/..:/code \
           -w /code \
           openstax/cookbook.ci:latest \
           /bin/bash -c "bundle config path vendor/bundle && bundle install && bundle exec rspec spec/kitchen_spec/"
