FROM ruby:2.6.6-buster AS runtime-env

RUN gem install bundler --no-document && \
    gem install byebug --no-document && \
    gem install rspec --no-document && \
    bundle config set no-cache 'true' && \
    bundle config set silence_root_warning 'true' && \
    rm -rf /var/lib/apt/lists/*

# Install gems which are needed to run each recipe
COPY . /code
RUN /code/scripts/install_used_gem_versions
WORKDIR /code
