#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

rm -rf /tmp/fake_kitchen_dir_to_mount

if (test -a $DIR/../.devcontainer/kitchen_path); then
  kitchen_dir=$(cat $DIR/../.devcontainer/kitchen_path)
else
  mkdir /tmp/fake_kitchen_dir_to_mount
  echo "To make this directory be your real kitchen directory, see the README" >> /tmp/fake_kitchen_dir_to_mount/where_is_kitchen.txt
  kitchen_dir=/tmp/fake_kitchen_dir_to_mount
fi

rm -f /tmp/kitchen
ln -s $kitchen_dir /tmp/kitchen
