#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

dependencies=( kitchen legacy_recipes )

for dependency in "${dependencies[@]}"
do
    fake_dependency_dir=/tmp/fake_"$dependency"_dir_to_mount
    rm -rf $fake_dependency_dir

    file_containing_real_dependency_dir=$DIR/../.devcontainer/"$dependency"_path

    if (test -a $file_containing_real_dependency_dir); then
      real_dependency_dir=$(cat $DIR/../.devcontainer/"$dependency"_path)
    else
      real_dependency_dir=/tmp/certainly_does_not_exist
    fi

    if (test -a $real_dependency_dir); then
      dependency_dir=$real_dependency_dir
    else
      mkdir $fake_dependency_dir
      echo "To make this directory be your real $dependency directory, see the README" >> $fake_dependency_dir/where_is_"$dependency".txt
      dependency_dir=$fake_dependency_dir
    fi

    rm -f /tmp/"$dependency"
    ln -s $dependency_dir /tmp/"$dependency"
done
