inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/BlockDelimiters:
  FunctionalMethods:
    - let
    - let!
    - subject
    - watch
    - expect # added this

Style/SymbolProc:
  Enabled: false
