# frozen_string_literal: true

module Kitchen::Directions::BakeAutotitledExercise
  class V1
    def bake(exercise:, number:)
      exercise.add_class('unnumbered') unless number

      # bake problem
      exercise.problem.wrap_children('div', class: 'os-problem-container')
      exercise.problem.prepend(child:
        <<~HTML
          <h4 class="exercise-title" data-type="title">#{exercise.autogenerated_title}</h4>
        HTML
      )
      return unless exercise.solution

      # bake solution in place
      exercise.solution.wrap_children('div', class: 'os-solution-container')
      exercise.solution.prepend(child:
        <<~HTML
          <h4 class="solution-title" data-type="title">
            <span class="os-text">#{I18n.t(:"exercises.solution")}</span>
          </h4>
        HTML
      )
    end
  end
end
