module Kitchen
  module Directions
    module BakeNotes

      def self.v1(book:)
        book.notes.each do |note|
          title = note.title

          if title.present?
            if note.indicates_autogenerated_title?
              note.append(child:
                <<~HTML
                  <h3 class="os-title" data-type="title">
                    <span class="os-title-label">#{note.autogenerated_title}</span>
                  </h3>
                HTML
              )

              title.name = "h4"
              title.add_class("os-subtitle")
              title.replace_children(with:
                <<~HTML
                  <span class="os-subtitle-label">#{title.children}</span>
                HTML
              )
            else
              title.name = "h3"
              title.add_class("os-title")
              title.replace_children(with:
                <<~HTML
                  <span data-type="" id="#{title.id}" class="os-title-label">#{title.children}</span>
                HTML
              )
              title.remove_attribute("id")
            end
          else
            note.append(child:
              <<~HTML
                <h3 class="os-title" data-type="title">
                  <span class="os-title-label">#{note.autogenerated_title}</span>
                </h3>
              HTML
            )
          end

          body = note.search("> :not(h3)").cut

          note.append(child:
            <<~HTML
              <div class="os-note-body">
                #{body.paste}
              </div>
            HTML
          )
        end
      end

    end
  end
end
