module Kitchen
  module Directions
    module ProcessNotes

      def self.v1(book:)
        book.notes.each do |note|
          # do spec with a missing title, use title hash
          # or should it be in NoteElement? no b/c this is a direction
          # could get note.generated_title_key -> use that in a locale file
          title = note.title

          if title.present?
            title.name = "h3"
            title.add_class("os-title")
            title.replace_children(with:
              <<~HTML
                <span data-type="" id="#{title.id}" class="os-title-label">#{title.children}</span>
              HTML
            )
            title.remove_attribute("id")
          else
            note.append(child:
              <<~HTML
                <h3 class="os-title" data-type="title">
                  <span class="os-title-label">#{note.autogenerated_title}</span>
                </h3>
              HTML
            )
          end

          body = note.search("> :not(h3)").cut

          note.append(child:
            <<~HTML
              <div class="os-note-body">
                #{body.paste}
              </div>
            HTML
          )
        end
      end

    end
  end
end
