#!/usr/bin/env ruby

# frozen_string_literal: true

require 'fileutils'

# Create locales directory and en.yml file with test data
def create_initial_locales(recipe_dir)
  File.write(
    "#{recipe_dir}/locales/en.yml",
    <<~YML
      en:
        sample: Text # remove this later
    YML
  )
end

# Create bake file
def create_initial_bake_script(recipe_dir, recipe)
  recipe_underscores = recipe.gsub('-', '_')
  File.write(
    "#{recipe_dir}/recipe.rb",
    <<~RUBY
      # frozen_string_literal: true

      #{recipe_underscores.upcase}_RECIPE = Kitchen::BookRecipe.new(book_short_name: :#{recipe_underscores}) do |doc, _resources|
        include Kitchen::Directions

        book = doc.book
        metadata = book.metadata

        book.search('cnx-pi').trash

        # Your recipe code goes here

        BakeFolio.v1(book: book)
      end
    RUBY
  )
end

ARGV.each do |recipe|
  recipe_dir = "#{Dir.pwd}/lib/recipes/#{recipe}"
  Dir.mkdir(recipe_dir)
  Dir.mkdir("#{recipe_dir}/locales")

  create_initial_locales(recipe_dir)
  create_initial_bake_script(recipe_dir, recipe)
end
