#!/usr/bin/env ruby

# Recipes all use different versions of kitchen, so we can't just use one
# Gemfile.  Pull each version of each gem used by the recipes out and manually
# install them.

require 'set'
require_relative '../kitchen_gem_versions'

# Install non-kitchen gems
puts `gem install activesupport -v '< 6.1'`

# Add gems and versions from book files
source_filenames = (Dir.glob(File.join(__dir__,"../books/**/*")) + [File.join(__dir__,"console"),File.join(__dir__,"normalize")])
                       .select{|filename| !File.directory?(filename)}

gem_name_to_versions_array_hash = source_filenames.each_with_object({}) do |filename,hash|
  source = File.read(filename, encoding: 'utf-8')
  gem_names_and_versions = source.scan(/gem\s+['"](\w+)['"]\s*,\s*(.+)['"](\d+\.\d+\.\d+)['"]/)
  gem_names_and_versions.each do |gem_name, _, version|
    (hash[gem_name] ||= Set.new([])).add(version)
  end
end

# Add remaining kitchen versions from KITCHEN_VERSIONS
KITCHEN_VERSIONS.each_value do |version|
  (gem_name_to_versions_array_hash['openstax_kitchen'] ||= Set.new([])).add(version)
end

gem_name_to_versions_array_hash.each do |gem_name, versions|
  versions.each do |version|
    command = "gem install #{gem_name} -v #{version}"
    puts command
    puts `#{command}`
  end
end
