#!/usr/bin/env ruby

# frozen_string_literal: true

require 'bundler/inline'
require_relative 'helpers/normalize_helpers'

gemfile do
  gem 'nokogiri', '>=1.7.0'
  gem 'byebug'
end

AVAILABLE_FLAGS = %w[--mask-terms].freeze

def process(input_file:, output_file:, args: [])
  read_and_write(input_file: input_file, output_file: output_file) do |doc|
    normalize(doc, args: args)
  end
end

def read_and_write(input_file:, output_file:)
  doc = Nokogiri::XML(File.open(input_file)) { |config| config.noblanks }

  yield(doc) if block_given?

  File.open(output_file, 'w') do |f|
    f.write doc.to_xhtml(indent: 2)
  end
end

ARGV.each do |input_file|
  next if AVAILABLE_FLAGS.include?(input_file)

  output_file =
    if File.extname(input_file) != ''
      input_file.gsub(/(\.\w+)\z/, '.normalized\1')
    else
      "#{input_file}.normalized"
    end

  process(input_file: input_file, output_file: output_file, args: ARGV & AVAILABLE_FLAGS)

  puts "Normalized '#{input_file}' to '#{output_file}'"
end
