#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../lib/recipes/recipes_helper'
require 'tempfile'

def read_and_write(input_file:, output_file:)
  doc = Nokogiri::XML(File.open(input_file)) { |config| config.noblanks }

  File.open(output_file, 'w') do |f|
    f.write doc.to_xhtml(indent: 2)
  end
end

ARGV.each do |input_file|
  tmp_output = Tempfile.new(input_file)
  read_and_write(input_file: input_file, output_file: tmp_output)
  FileUtils.cp(tmp_output, input_file)

  puts "Normalized '#{input_file}'"
end
