#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../lib/recipes/recipes_helper'

def read_and_write(input_file:, output_file:)
  doc = Nokogiri::XML(File.open(input_file)) { |config| config.noblanks }

  File.open(output_file, 'w') do |f|
    f.write doc.to_xhtml(indent: 2)
  end
end

ARGV.each do |input_file|
  output_file =
    if File.extname(input_file) != ''
      input_file.gsub(/(\.\w+)\z/, '.normalized\1')
    else
      "#{input_file}.normalized"
    end

  read_and_write(input_file: input_file, output_file: output_file)

  puts "Normalized '#{input_file}' to '#{output_file}'"
end
