# frozen_string_literal: true

require 'spec_helper'

RSpec.describe Kitchen::Directions::BakeLOLinkLabels do

  let(:book_with_lo_reference_links_and_custom_module_target_labels) do
    book_containing(html:
      <<~HTML
        <a>skip this link</a>
        <a href='?key'>Example x.y</a>
        <a class='lo-reference autogenerated-content' href='?other_key'>
          <span class="label-counter">x.y</span>
          <span class="title-label-text">Some Module Title</span>
        </a>
      HTML
    )
  end

  before do
    stub_locales({
      'lo_label_text': 'LO '
    })
  end

  it 'bakes book with custom modules target labels' do
    described_class.v1(book: book_with_lo_reference_links_and_custom_module_target_labels)
    expect(book_with_lo_reference_links_and_custom_module_target_labels.body).to match_snapshot_auto
  end
end
