#!/usr/bin/env ruby

require_relative '../recipes_helper'

I18n.locale = 'zz'

recipe = Kitchen::BookRecipe.new(book_short_name: :dummy) do |doc|
  include Kitchen::Directions

  book = doc.book
  book.search('div.test123').each { |div| div.replace_children(with: 'Hello, world!') }
end

opts = Slop.parse do |slop|
  slop.string '--input', 'Assembled XHTML input file', required: true
  slop.string '--output', 'Baked XHTML output file', required: true
end

puts Kitchen::Oven.bake(
  input_file: opts[:input],
  recipes: recipe,
  output_file: opts[:output]
)
