require 'spec_helper'

RSpec.describe Kitchen::Directions::ProcessNotes do

  let(:book_1) do
    book_containing(
      one_chapter_with_one_page_containing(
        <<~HTML
          <div data-type="note" id="noteId">
            <div data-type="title" id="titleId"><em>Answer:</em></div>
            <p id="pId">Blah</p>
          </div>
        HTML
      )
    )
  end

  context "v1" do
    it "works" do
      described_class.v1(book: book_1, autogenerated_titles: {})

      expect(book_1.elements("[data-type='note']").first).to match_html(
        <<~HTML
          <div data-type="note" id="noteId">
            <h3 class="os-title" data-type="title">
              <span data-type="" id="titleId" class="os-title-label"><em>Answer:</em></span>
            </h3>
            <div class="os-note-body">
              <p id="pId">Blah</p>
            </div>
          </div>
        HTML
      )
    end

  end
end
