name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kitchen_tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build docker image and run kitchen specs + codecov within it
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        # See https://docs.codecov.io/docs/testing-with-docker
        run: |
          ./docker/build --ci
          CI_ENV=`bash <(curl -s https://codecov.io/env)` ./docker/ci_kitchen
  recipes_tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build docker image and run recipes specs within it
        run: |
          ./docker/build --ci
          ./docker/ci_recipes
